name: Func Check Generated

on: [pull_request]

jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.x"
      - name: Check that 'schema/func_yaml-schema.json schema' is up-to-date
        run: make clean && schema-modified-check
      - name: Check that 'templates/certs/ca-certificates.crt' is up-to-date
        run: make clean && certs-modified-check
      - name: Check that 'generate/zz_filesystem_generated.go' is up-to-date
        run: make clean && templates-modified-check
